name: helloworld
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

    # web_socket_channel: ^3.0.0

  # --- Video Player (Versi Baru Support Null Safety) ---
  flutter_mjpeg: ^2.0.4

  # --- Icon (Versi 2.0.5 agar akur dengan mjpeg) ---
  flutter_svg: 2.0.5
  
  webview_flutter: ^4.8.0

  # --- Library Lainnya ---
  flutter_blue_plus: ^1.32.11
  wifi_iot: ^0.3.19
  permission_handler: ^11.3.1
  get: ^4.6.6  
  connectivity_plus: ^6.1.0
  network_info_plus: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - img/